# Exercise 1 - Now, using the LinearRegression (sklearn) function of Python
# create a regression model and calculate metrics like R2, MAE,
# RMSE and analyze the results
# Further, use the OLS function from 'statsmodels' package to
# perform regression, print the results and review them.

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score


In [2]:
# 1. Load the data from a CSV file
try:
    df = pd.read_csv('..\\data2\\data-set-for-SLR-2025.csv')  # Replace 'your_data.csv' with your actual file name
except FileNotFoundError:
    print("Error: 'your_data.csv' not found. Please ensure the file exists in the correct directory.")
    exit()

print ("Got Data \n", df.head())

Got Data 
           y         x
0  7.238462  0.025641
1  6.310256  0.051282
2  8.315385  0.076923
3  4.787179  0.102564
4  5.592308  0.128205


In [5]:
print(df['x'][0], ' ', df['y'][0])

0.025641026   7.238461538


In [9]:
# Assuming 'feature_column' is your independent variable and 'target_column' is your dependent variable
# Adjust these column names based on your CSV file
X = df[['x']]  # Features (independent variables)
y = df['y']   # Target variable (dependent variable)

# 2. Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. Create and train the Linear Regression model
model = LinearRegression()
model.fit(X_train, y_train)

# 4. Make predictions on the test set
y_pred = model.predict(X_test)

# 5. Calculate evaluation metrics
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

print(f"R-squared (R2): {r2:.4f}")
print(f"Mean Absolute Error (MAE): {mae:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")

R-squared (R2): 0.8525
Mean Absolute Error (MAE): 1.5754
Root Mean Squared Error (RMSE): 1.8518


In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import root_mean_squared_error, r2_score
import statsmodels.api as sm
import matplotlib.pyplot as plt

In [2]:
help(PolynomialFeatures)

Help on class PolynomialFeatures in module sklearn.preprocessing._polynomial:

class PolynomialFeatures(sklearn.base.TransformerMixin, sklearn.base.BaseEstimator)
 |  PolynomialFeatures(
 |      degree=2,
 |      *,
 |      interaction_only=False,
 |      include_bias=True,
 |      order='C'
 |  )
 |
 |  Generate polynomial and interaction features.
 |
 |  Generate a new feature matrix consisting of all polynomial combinations
 |  of the features with degree less than or equal to the specified degree.
 |  For example, if an input sample is two dimensional and of the form
 |  [a, b], the degree-2 polynomial features are [1, a, b, a^2, ab, b^2].
 |
 |  Read more in the :ref:`User Guide <polynomial_features>`.
 |
 |  Parameters
 |  ----------
 |  degree : int or tuple (min_degree, max_degree), default=2
 |      If a single int is given, it specifies the maximal degree of the
 |      polynomial features. If a tuple `(min_degree, max_degree)` is passed,
 |      then `min_degree` is the mini

In [6]:
X = np.arange(6).reshape(2, 3)
print( ' original x ', X)
print(" == == == ")
poly = PolynomialFeatures(2)
v1 = poly.fit_transform(X)
print(v1)
v2 = poly.transform(X)
print(v2)
print(" == == == ")
poly = PolynomialFeatures(3)
v1 = poly.fit_transform(X)
print(v1)
v2 = poly.transform(X)
print(v2)
print(" == == == ")


 original x  [[0 1 2]
 [3 4 5]]
 == == == 
[[ 1.  0.  1.  2.  0.  0.  0.  1.  2.  4.]
 [ 1.  3.  4.  5.  9. 12. 15. 16. 20. 25.]]
[[ 1.  0.  1.  2.  0.  0.  0.  1.  2.  4.]
 [ 1.  3.  4.  5.  9. 12. 15. 16. 20. 25.]]
 == == == 
[[  1.   0.   1.   2.   0.   0.   0.   1.   2.   4.   0.   0.   0.   0.
    0.   0.   1.   2.   4.   8.]
 [  1.   3.   4.   5.   9.  12.  15.  16.  20.  25.  27.  36.  45.  48.
   60.  75.  64.  80. 100. 125.]]
[[  1.   0.   1.   2.   0.   0.   0.   1.   2.   4.   0.   0.   0.   0.
    0.   0.   1.   2.   4.   8.]
 [  1.   3.   4.   5.   9.  12.  15.  16.  20.  25.  27.  36.  45.  48.
   60.  75.  64.  80. 100. 125.]]
 == == == 
